version = 0.1
[default.deploy.parameters]
stack_name = "genai-app-boilerplate"
resolve_s3 = true
s3_prefix = "genai-app-boilerplate"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Frontend=\"local\" Repository=\"\""
image_repositories = []
